filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/stardust/app.json
  fields:
    logtype: application
    service: stardust-api
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true
  multiline.pattern: '^{'
  multiline.negate: true
  multiline.match: after

- type: log
  enabled: true
  paths:
    - /var/log/stardust/errors.json
  fields:
    logtype: error
    service: stardust-api
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true
  multiline.pattern: '^{'
  multiline.negate: true
  multiline.match: after

- type: log
  enabled: true
  paths:
    - /var/log/stardust/security.json
  fields:
    logtype: security
    service: stardust-api
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true
  multiline.pattern: '^{'
  multiline.negate: true
  multiline.match: after

- type: log
  enabled: true
  paths:
    - /var/log/stardust/performance.json
  fields:
    logtype: performance
    service: stardust-api
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true
  multiline.pattern: '^{'
  multiline.negate: true
  multiline.match: after

- type: docker
  enabled: true
  containers.ids:
    - "*"
  containers.path: "/var/lib/docker/containers"
  containers.stream: "all"
  fields:
    logtype: docker
  fields_under_root: true

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_docker_metadata: ~
- add_kubernetes_metadata: ~
- timestamp:
    field: timestamp
    layouts:
      - '2006-01-02T15:04:05.000Z'
      - '2006-01-02T15:04:05Z'
    test:
      - '2023-12-01T10:30:45.123Z'

output.elasticsearch:
  hosts: ["stardust-elasticsearch:9200"]
  index: "stardust-api-%{+yyyy.MM.dd}"

setup.template.name: "stardust-api"
setup.template.pattern: "stardust-api-*"
setup.template.enabled: true
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0
  index.refresh_interval: "5s"
setup.template.mappings:
  properties:
    timestamp:
      type: date
    level:
      type: keyword
    message:
      type: text
      analyzer: standard
    event_type:
      type: keyword
    request_id:
      type: keyword
    user_id:
      type: keyword
    client_ip:
      type: ip
    duration_ms:
      type: float
    status_code:
      type: integer
    method:
      type: keyword
    path:
      type: keyword
    error_type:
      type: keyword
    logtype:
      type: keyword
    service:
      type: keyword

setup.kibana:
  host: "stardust-kibana:5601"

setup.dashboards.enabled: true

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644 