version: '3.8'

services:
  ava4-mqtt-listener:
    build:
      context: ./services/mqtt-listeners/ava4-listener
      dockerfile: Dockerfile
    container_name: ava4-mqtt-listener
    environment:
      - MQTT_BROKER_HOST=adam.amy.care
      - MQTT_BROKER_PORT=1883
      - MQTT_USERNAME=webapi
      - MQTT_PASSWORD=Sim!4433
      - MQTT_TOPICS=ESP32_BLE_GW_TX,dusun_sub
      - MONGODB_URI=mongodb://opera_admin:Sim!443355@coruscant.my-firstcare.com:27023/admin?ssl=true&authSource=admin
      - MONGODB_DATABASE=AMY
      - LOG_LEVEL=DEBUG
    restart: unless-stopped
    networks:
      - stardust-network
    depends_on:
      - stardust-api

  kati-mqtt-listener:
    build:
      context: ./services/mqtt-listeners/kati-listener
      dockerfile: Dockerfile
    container_name: kati-mqtt-listener
    environment:
      - MQTT_BROKER_HOST=adam.amy.care
      - MQTT_BROKER_PORT=1883
      - MQTT_USERNAME=webapi
      - MQTT_PASSWORD=Sim!4433
              - MQTT_TOPICS=iMEDE_watch/VitalSign,iMEDE_watch/AP55,iMEDE_watch/hb,iMEDE_watch/location,iMEDE_watch/sleepdata,iMEDE_watch/sos,iMEDE_watch/SOS,iMEDE_watch/fallDown,iMEDE_watch/fallDown,iMEDE_watch/onlineTrigger
      - MONGODB_URI=mongodb://opera_admin:Sim!443355@coruscant.my-firstcare.com:27023/admin?ssl=true&authSource=admin
      - MONGODB_DATABASE=AMY
      - LOG_LEVEL=DEBUG
    restart: unless-stopped
    networks:
      - stardust-network
    depends_on:
      - stardust-api

  qube-mqtt-listener:
    build:
      context: ./services/mqtt-listeners/qube-listener
      dockerfile: Dockerfile
    container_name: qube-mqtt-listener
    environment:
      - MQTT_BROKER_HOST=adam.amy.care
      - MQTT_BROKER_PORT=1883
      - MQTT_USERNAME=webapi
      - MQTT_PASSWORD=Sim!4433
      - MQTT_TOPICS=CM4_BLE_GW_TX
      - MONGODB_URI=mongodb://opera_admin:Sim!443355@coruscant.my-firstcare.com:27023/admin?ssl=true&authSource=admin
      - MONGODB_DATABASE=AMY
      - LOG_LEVEL=DEBUG
    restart: unless-stopped
    networks:
      - stardust-network
    depends_on:
      - stardust-api

networks:
  stardust-network:
    external: true 