apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://stardust-elasticsearch:9200
    database: "logstash-*"
    basicAuth: false
    isDefault: true
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 7 