http.host: "0.0.0.0"
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["http://stardust-elasticsearch:9200"]
path.config: /usr/share/logstash/pipeline
path.logs: /var/log/logstash 